name: test_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - anndata2ri=1.0.2=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - blas=2.14=openblas
  - bleach=3.1.0=py37_0
  - blosc=1.16.3=hd408876_0
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2019.11.28=py37_1
  - cffi=1.14.0=py37h2e261b9_0
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - get_version=2.1=py_1
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_9
  - glib=2.63.1=h5a9c865_0
  - gmp=6.2.0=he1b5a44_2
  - graphite2=1.3.13=h23475e2_0
  - gsl=2.6=h294904e_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5py=2.10.0=py37h7918eee_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=64.2=he1b5a44_1
  - igraph=0.7.1=h9e3b1fc_1007
  - importlib-metadata=1.5.0=py37hc8dfbb8_1
  - importlib_metadata=1.5.0=py37_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.0.0=py_0
  - jupyter_core=4.6.1=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=hee79883_0
  - llvmlite=0.31.0=py37hd408876_0
  - louvain=0.6.1=py37he1b5a44_2
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - make=4.2.1=h1bed415_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37h30547a4_0
  - mistune=0.8.4=py37h7b6447c_0
  - mock=4.0.1=py_0
  - natsort=7.0.1=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - networkx=2.4=py_0
  - notebook=6.0.3=py37_0
  - numba=0.48.0=py37h0573a6f_0
  - numexpr=2.7.1=py37h7ea95a0_0
  - numpy=1.18.1=py37h94c655d_0
  - numpy-base=1.18.1=py37h2f8d375_1
  - openssl=1.1.1f=h7b6447c_0
  - pandas=1.0.3=py37h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=ha030887_1
  - parso=0.6.2=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py37_0
  - pycairo=1.19.0=py37h2a1e443_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.7=py37h7b6447c_0
  - pytables=3.6.1=py37h71ec239_0
  - python=3.7.6=h8356626_5_cpython
  - python-dateutil=2.8.1=py_0
  - python-igraph=0.8.0=py37hb78272c_1
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h0c104cb_3
  - r-askpass=1.0=r36h14c3975_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-backports=1.1.4=r36h96ca727_0
  - r-base=3.6.2=h7ed4ef7_1
  - r-base64enc=0.1_3=r36h96ca727_4
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-broom=0.5.2=r36h6115d3f_0
  - r-callr=3.2.0=r36h6115d3f_0
  - r-caret=6.0_83=r36h96ca727_0
  - r-cellranger=1.1.0=r36h6115d3f_0
  - r-class=7.3_15=r36h96ca727_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-clipr=0.6.0=r36h6115d3f_0
  - r-cluster=2.0.8=r36ha65eedd_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h96ca727_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-curl=3.3=r36h96ca727_0
  - r-data.table=1.12.2=r36h96ca727_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h96ca727_0
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-ellipsis=0.1.0=r36h96ca727_0
  - r-essentials=3.6.0=r36_0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-fansi=0.4.0=r36h96ca727_0
  - r-forcats=0.4.0=r36h6115d3f_0
  - r-foreach=1.4.4=r36h6115d3f_0
  - r-foreign=0.8_71=r36h96ca727_0
  - r-formatr=1.6=r36h6115d3f_0
  - r-fs=1.2.7=r36h29659fb_0
  - r-generics=0.0.2=r36h6115d3f_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glmnet=2.0_16=r36ha65eedd_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-gower=0.2.0=r36h96ca727_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-haven=2.1.0=r36h29659fb_0
  - r-hexbin=1.27.2=r36ha65eedd_0
  - r-highr=0.8=r36h6115d3f_0
  - r-hms=0.4.2=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h29659fb_0
  - r-htmlwidgets=1.3=r36h6115d3f_0
  - r-httpuv=1.5.1=r36h29659fb_0
  - r-httr=1.4.0=r36h6115d3f_0
  - r-ipred=0.9_8=r36h96ca727_0
  - r-irdisplay=0.7.0=r36h6115d3f_0
  - r-irkernel=0.8.15=r36_0
  - r-iterators=1.0.10=r36h6115d3f_0
  - r-jsonlite=1.6=r36h96ca727_0
  - r-kernsmooth=2.23_15=r36ha65eedd_4
  - r-knitr=1.22=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-later=0.8.0=r36h29659fb_0
  - r-lattice=0.20_38=r36h96ca727_0
  - r-lava=1.6.5=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36h96ca727_0
  - r-lubridate=1.7.4=r36h29659fb_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-maps=3.3.0=r36h96ca727_0
  - r-markdown=0.9=r36h96ca727_0
  - r-mass=7.3_51.3=r36h96ca727_0
  - r-matrix=1.2_17=r36h96ca727_0
  - r-mgcv=1.8_28=r36h96ca727_0
  - r-mime=0.6=r36h96ca727_0
  - r-modelmetrics=1.2.2=r36h29659fb_0
  - r-modelr=0.1.4=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-nnet=7.3_12=r36h96ca727_0
  - r-numderiv=2016.8_1=r36h6115d3f_0
  - r-openssl=1.3=r36h96ca727_0
  - r-pbdzmq=0.3_3=r36h559a7a4_1002
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h29659fb_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-processx=3.3.0=r36h96ca727_0
  - r-prodlim=2018.04.18=r36h29659fb_0
  - r-progress=1.2.0=r36h6115d3f_0
  - r-promises=1.0.1=r36h29659fb_0
  - r-ps=1.3.0=r36h96ca727_0
  - r-purrr=0.3.2=r36h96ca727_0
  - r-quantmod=0.4_14=r36h6115d3f_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-randomforest=4.6_14=r36ha65eedd_0
  - r-rbokeh=0.6.3=r36_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-rcpproll=0.3.0=r36h29659fb_0
  - r-readr=1.3.1=r36h29659fb_0
  - r-readxl=1.3.1=r36h29659fb_0
  - r-recipes=0.1.5=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-rematch=1.0.1=r36h6115d3f_0
  - r-repr=0.19.2=r36h6115d3f_0
  - r-reprex=0.2.1=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h29659fb_0
  - r-rlang=0.3.4=r36h96ca727_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-rpart=4.1_15=r36h96ca727_0
  - r-rstudioapi=0.10=r36h6115d3f_0
  - r-rvest=0.3.3=r36h6115d3f_0
  - r-scales=1.0.0=r36h29659fb_0
  - r-selectr=0.4_1=r36h6115d3f_0
  - r-shiny=1.3.2=r36h6115d3f_0
  - r-sourcetools=0.1.7=r36h29659fb_0
  - r-spatial=7.3_11=r36h96ca727_4
  - r-squarem=2017.10_1=r36h6115d3f_0
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-survival=2.44_1.1=r36h96ca727_0
  - r-sys=3.2=r36h96ca727_0
  - r-tibble=2.1.1=r36h96ca727_0
  - r-tidyr=0.8.3=r36h29659fb_0
  - r-tidyselect=0.2.5=r36h29659fb_0
  - r-tidyverse=1.2.1=r36h6115d3f_0
  - r-timedate=3043.102=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-ttr=0.23_4=r36ha65eedd_0
  - r-utf8=1.1.4=r36h96ca727_0
  - r-uuid=0.1_2=r36h96ca727_4
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-whisker=0.3_2=r36h6115d3f_4
  - r-withr=2.1.2=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-xml2=1.2.0=r36h29659fb_0
  - r-xtable=1.8_4=r36h6115d3f_0
  - r-xts=0.11_2=r36h96ca727_0
  - r-yaml=2.2.0=r36h96ca727_0
  - r-zoo=1.8_6=r36h96ca727_0
  - readline=8.0=h7b6447c_0
  - rpy2=3.1.0=py37r36hc1659b7_3
  - scikit-learn=0.22.1=py37h22eb022_0
  - scipy=1.4.1=py37habc2bb6_0
  - seaborn=0.10.0=py_0
  - sed=4.7=h1bed415_1000
  - send2trash=1.5.0=py37_0
  - setuptools=46.1.1=py37_0
  - simplegeneric=0.8.1=py37_2
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - snappy=1.1.7=hbae5bb6_3
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.11.0=py37h7b6447c_0
  - tbb=2020.0=hfd86e86_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - texttable=1.6.2=py_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h14c3975_0
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py37_0
  - tzlocal=2.0.0=py37_0
  - umap-learn=0.3.10=py37_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.2=he1b5a44_2
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - anndata==0.7.1
    - legacy-api-wrap==1.2
    - packaging==20.3
    - scanpy==1.4.5.2.dev6+gfa408dc7
    - setuptools-scm==3.5.0
prefix: /home/maria/miniconda3/envs/test_env

